[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
httparse = "1.8.0"
bytes = "1.2"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
reqwest = "0.12.4"
hyper-tls = "0.6.0"
